### ISSUE TITLE
Where can I get dtm and sat images?

### ISSUE THREAD

**Issue by thecuder** [wonder-sk/qgis3d#5]
Where can I get dtm and sat images? I used https://earthexplorer.usgs.gov/ to get dtm image but it i dont know how to get a sat image that fit with dtm image?

**Comment by wonder-sk** [comment]
That's a very broad question...

USGS is good for DTMs. For satellite imagery, there are various sources with different resolution/quality, some are available just for particular areas, others for the whole world. Sometimes people use XYZ tiles layer with Bing/Google satellite imagery, but that may not comply with their terms&conditions.

I am closing this ticket as it is not directly related to the code.

**Comment by thuanvvh** [comment]
Thank you so much!

2018-01-29 15:28 GMT+07:00 Martin Dobias <notifications@github.com>:
